web/router.ex
defmodule EsExplorer.Router do
  use EsExplorer.Web, :router

  pipeline :browser do
    plug :accepts, ["html"]
    plug :fetch_session
    plug :fetch_flash
    plug :protect_from_forgery
    plug :put_secure_browser_headers
  end

  pipeline :api do
    plug :accepts, ["json"]
  end

  scope "/", EsExplorer do
    pipe_through :browser # Use the default browser stack

    get "/", PageController, :index
    post "/set_endpoints", PageController, :set_cookies
    get "/index_info", IndexInfoController, :index
    get "/index_settings", IndexInfoController, :settings

    get "/search/lite", SearchController, :lite
    post "/search/run_search", SearchController, :run_search
  end

  # Other scopes may use custom stacks.
  # scope "/api", EsExplorer do
  #   pipe_through :api
  # end
end

lib/es_explorer/endpoint.ex
defmodule EsExplorer.Endpoint do
  use Phoenix.Endpoint, otp_app: :es_explorer

  socket "/socket", EsExplorer.UserSocket

  # Serve at "/" the static files from "priv/static" directory.
  #
  # You should set gzip to true if you are running phoenix.digest
  # when deploying your static files in production.
  plug Plug.Static,
    at: "/", from: :es_explorer, gzip: false,
    only: ~w(css fonts images js favicon.ico robots.txt)

  # Code reloading can be explicitly enabled under the
  # :code_reloader configuration of your endpoint.
  if code_reloading? do
    socket "/phoenix/live_reload/socket", Phoenix.LiveReloader.Socket
    plug Phoenix.LiveReloader
    plug Phoenix.CodeReloader
  end

  plug Plug.RequestId
  plug Plug.Logger

  plug Plug.Parsers,
    parsers: [:urlencoded, :multipart, :json],
    pass: ["*/*"],
    json_decoder: Poison

  plug Plug.MethodOverride
  plug Plug.Head

  plug Plug.Session,
    store: :cookie,
    key: "_es_explorer_key",
    signing_salt: "+4v7HDEA"

  plug EsExplorer.Router
end

lib/es_explorer/repo.ex
defmodule EsExplorer.Repo do
  use Ecto.Repo, otp_app: :es_explorer
end

web/controllers/index_info_controller.ex
defmodule EsExplorer.IndexInfoController do
  use EsExplorer.Web, :controller

  def index(conn, _params) do

    local_host = "localhost:9200"
    url = "http://#{local_host}/_cat/indices"
    local_response = HTTPotion.get url
    # want to parse this, and construct links to the settings page for each detected index
    list = String.split(local_response.body, "\n")
#    ul = []
#    Enum.each(list, fn(x) -> ul = ul ++ ["<li>#{x}</li>"] end)

    render conn, "index.html", list: list
  end

  def settings(conn, params) do
    name = params["index"]
    local_host = "localhost:9200"
    prod_host = "localhost:9200" # figure out how to load this from a config file--do not check in prod url!!!

    live_response = HTTPotion.get  "http://#{prod_host}/#{name}/_settings?pretty=true"

    local_response = HTTPotion.get "http://#{local_host}/#{name}/_settings?pretty=true"

    render conn, "settings.html", name: name, live: live_response.body, local: local_response.body
  end
end

web/controllers/page_controller.ex
defmodule EsExplorer.PageController do
  use EsExplorer.Web, :controller

  def index(conn, _params) do
    render conn, "index.html"
  end

  def set_cookies(conn, params) do
    local = params["page"]["local_endpoint"]
    ext = params["page"]["ext_endpoint"]

    conn |> put_resp_cookie("local_endpoint", local)
         |> put_resp_cookie("ext_endpoint", ext)
         |> render "index.html"
  end
end

web/controllers/search_controller.ex
defmodule EsExplorer.SearchController do
  use EsExplorer.Web, :controller

  def lite(conn, _params) do
    # form to create search to submit, can only specify index and simple query
    render conn, "lite.html", data: "", index: "", query: ""
  end

  def run_search(conn, params) do
    # run the search and render the results
    search = params["search"]
    index = search["index"]
    query = search["query"]

    local_host = "localhost:9200"

    local_response = HTTPotion.get "http://#{local_host}#{index}/_search?q=#{URI.encode(query)}"
#    local_response = HTTPotion.get "http://localhost:9200/_search?q=register"

    render conn, "lite.html", data: local_response.body, index: index, query: query
  end
end

web/views/error_view.ex
defmodule EsExplorer.ErrorView do
  use EsExplorer.Web, :view

  def render("404.html", _assigns) do
    "Page not found"
  end

  def render("500.html", _assigns) do
    "Server internal error"
  end

  # In case no render clause matches or no
  # template is found, let's render it as 500
  def template_not_found(_template, assigns) do
    render "500.html", assigns
  end
end

web/views/index_info_view.ex
defmodule EsExplorer.IndexInfoView do
  use EsExplorer.Web, :view

  def echo_list(list) do
    list
  end
end

web/views/layout_view.ex
defmodule EsExplorer.LayoutView do
  use EsExplorer.Web, :view
end

web/views/page_view.ex
defmodule EsExplorer.PageView do
  use EsExplorer.Web, :view

  def cookies(conn, cookie_name) do
    conn.cookies[cookie_name]
  end
end

web/views/search_view.ex
defmodule EsExplorer.SearchView do
  use EsExplorer.Web, :view

end

web/templates/index_info/index.html.eex
<p>current indexes</p>

<ul>
  <%= for el <- echo_list(@list) do %>
    <li><%= el %></li>
  <% end %>
</ul>

web/templates/index_info/settings.html.eex
<p>index settings for <%= @name %></p>

<div style="width: 49%; float: left">
  <p>Production Settings</p>
  <pre><%= @live %></pre>
</div>

<div style="width: 49%; float: left">
  <p>Local Settings</p>
  <pre><%= @local %></pre>
</div>

<div style="clear: both"></div>

web/templates/layout/app.html.eex
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="A simple tool for exploring ElasticSearch">
    <meta name="author" content="Brandy Webster">

    <title>EsExplorer</title>
    <link rel="stylesheet" href="<%= static_path(@conn, "/css/app.css") %>">
  </head>

  <body>
    <div class="container">
      <header class="header">
        <nav role="navigation">
          <ul class="nav nav-pills pull-right">
            <li><a href="/">Home</a></li>
          </ul>
        </nav>
        <span class="logo"></span>
      </header>

      <p class="alert alert-info" role="alert"><%= get_flash(@conn, :info) %></p>
      <p class="alert alert-danger" role="alert"><%= get_flash(@conn, :error) %></p>

      <main role="main">
        <%= render @view_module, @view_template, assigns %>
      </main>

    </div> <!-- /container -->
    <script src="<%= static_path(@conn, "/js/app.js") %>"></script>
  </body>
</html>

web/templates/page/index.html.eex
<div class="jumbotron">
  <h2><%= gettext "Welcome to %{name}", name: "ES Explorer!" %></h2>
  <p class="lead">A simple tool for exploring<br />your elasticsearch data and structure.</p>
</div>

<div class="row">
  <%= form_for @conn, page_path(@conn, :set_cookies), [as: :page], fn f -> %>
    <div class="col-md-5">
      <p>Local ES Location:</p>
      <%= text_input f, :local_endpoint, value: cookies(@conn, "local_endpoint") %>
    </div>
    <div class="col-md-5">
      <p>External ES Location:</p>
      <%= text_input f, :ext_endpoint, value: cookies(@conn, "ext_endpoint") %>
    </div>
    <div class="col-md-2">
      <input type="Submit" value="Update" />
    </div>
  <% end %>
</div>

<div class="row">
  <div class="col-lg-6">
    <h4>Analysis</h4>
    <ul>
      <li>
        <a href="/index_info">Indices</a>
      </li>
      <li>
        <a href="/index_settings">Settings</a>
      </li>
    </ul>
  </div>

  <div class="col-lg-6">
    <h4>Searching</h4>
    <ul>
      <li>
        <a href="/search/lite">Lite Search</a>
      </li>
    </ul>
  </div>
</div>

web/templates/search/lite.html.eex
<h4>'Lite' Search</h4>

<p>Use this search page to perform basic search queries, either of raw text or of the form attr:value, as in the examples below:</p>

<ul>
  <li>john</li>
  <li>tweet:elasticsearch</li>
  <li>+name:john +tweet:mary</li>
  <li>+name:(mary john) +date:>2014-09-10 +(aggregations geo)</li>
</ul>

<%= form_for @conn, search_path(@conn, :run_search), [as: :search], fn f -> %>
  <label for="index">Index</label>
  <%= text_input f, :index %>
  <br />
  <label for="query">Query</label>
  <%= text_input f, :query %>
  <br />
  <%= submit "Search" %>
<% end %>

<p>Searched <%= @index %> for <%= @query %></p>
<%= @data %>